language: node_js
node_js:
- '0.10'
services:
- mongodb
before_script:
- sleep 15
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: Z/TWQOtICpElRmi2+nICYfaoW2l1ULCXVwdZugbRA5zW6rbsaw/LJO+IAEyAjrdwANco9+mddh3jihImD3/NCAch/B3iSblBvbNEZAMdGcQ8ET3HrcG1YmT0gjftfM6EXsTG6ruil1zaLbmVG4jUNd+hIAXj3a9KEqN9Y3phaPk=
app: 
    develop: codejames
    master: codejam
